CREATE TABLE PERSON

(ID INT NOT NULL,

USERNAME VARCHAR(50) NOT NULL,

FIRSTNAME VARCHAR(50) NOT NULL,

LASTNAME VARCHAR(50) NOT NULL,

JOB_POSITION VARCHAR(100) NOT NULL,

DOB DATE NOT NULL,

EMAIL VARCHAR(100) NOT NULL,

PRIMARY KEY (ID),

UNIQUE(USERNAME, EMAIL))